name: Flutter

on:
  # Runs this action when you push on main
  push:
    branches: ["main"]
  # Runs this when a PR against main is created
  pull_request:
    branches: ["main"]

jobs:
  flutter_build_test:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: run tests
        run: flutter test --coverage
        continue-on-error: true

      - name: Report Comment
        uses: kefasjw/lcov-pull-request-report@v1
        with:
          # Lcov file location. For example, coverage/lcov.info
          lcov-file: coverage/lcov.info
          # Github token required for getting list of changed files and posting comments
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-title: Coverage Report
          all-files-minimum-coverage: 50
          changed-files-minimum-coverage: 25
