name: Flutter

on:
  # Runs this action when you push on main
  push:
    branches: ["main"]
  # Runs this when a PR against main is created
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: run tests
        run: flutter test --coverage
        continue-on-error: true

      - name: Report Comment
        uses: kefasjw/lcov-pull-request-report@v1
        continue-on-error: true
        with:
          # Lcov file location. For example, coverage/lcov.info
          lcov-file: coverage/lcov.info
          # Github token required for getting list of changed files and posting comments
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-title: Coverage Report
          all-files-minimum-coverage: 10
          changed-files-minimum-coverage: 10

  build:
    name: Build Web
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install dependencies
        run: flutter pub get
      - name: Build Flutter web
        run: flutter build web
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web/

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
